#!/bin/bash
#================================================
#================================================
#   O.S.      : Gnu Linux                       =
#   Author    : Cristian Pozzessere   = ilnanny =
#   D.A.Page  : http://ilnanny.deviantart.com   =
#   Github    : https://github.com/ilnanny      =
#================================================
#Project:EvolvereMix
#================================================
#
#cd ..
set -o errexit
[[ $(whoami) == 'root' ]] || exec sudo su -c $0 root
#
echo "----------------------------------------------"
echo "Copio il tema delle icone in /usr/share/icons"
echo "----------------------------------------------"
cp -a -r /media/Dati/Git/EvolvereMix /usr/share/icons/
sleep 2 &&
echo "----------------------------------------------"
echo "      Installo  Lila HD Cursor"
echo "----------------------------------------------"
cp -a -r /media/Dati/Git/EvolvereMix/Lila_HD-cursor/ /usr/share/icons/
rm -r /usr/share/icons/EvolvereMix/Lila_HD-cursor
rm -r /usr/share/icons/EvolvereMix/.git
echo "----------------------------------------------"
echo "Tema di icone e cursore installato ,enjoy :D"
echo "----------------------------------------------"
exit 4
